services:
  acc_bot:
    image: "acc/bot:telegram"
    pull_policy: never
    environment:
      TELEGRAM_ACCESS_TOKEN: ${TELEGRAM_ACCESS_TOKEN}
      ACCOUNTANT_BOT_ACCESS_TOKEN: ${ACCOUNTANT_BOT_ACCESS_TOKEN}
      ALLOWED_USERS: ${ALLOWED_USERS}
      HOST_DOMAIN: ${HOST_DOMAIN}
    restart: unless-stopped
    networks:
      - proxy_bot-network
    dns:
      - 4.4.4.4
      - 8.8.8.8
    volumes:
      - ./accountant.db:/app/accountant.db
      - ./appsettings.json:/app/appsettings.json
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  proxy_bot-network:
    external: true